apiVersion: flagger.app/v1beta1
kind: MetricTemplate
metadata:
  name: error-rate
  namespace: ingress-nginx
spec:
  provider:
    type: prometheus
    address: http://thanos-query.monitoring.svc.cluster.local:9090
  query: |
    100 - sum(
      rate(
        nginx_ingress_controller_requests{
          exported_namespace="{{ namespace }}",
          ingress="{{ ingress }}",
          status!~"5.*"
        }[{{ interval }}]
      )
    ) 
    / 
    sum(
      rate(
        nginx_ingress_controller_requests{
          exported_namespace="{{ namespace }}",
          ingress="{{ ingress }}"
        }[{{ interval }}]
      )
    ) 
    * 100