apiVersion: v1
kind: Service
metadata:
  labels:
    app: podinfo
  name: podinfo
  namespace: test
spec:
  ports:
  - name: port-1
    port: 80
    protocol: TCP
    targetPort: 9898
  selector:
    app: podinfo
  sessionAffinity: None
  type: ClusterIP
